import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* Header */}

     <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
      {/* Left */}
      <div className='flex space-x-4 items-center'>
        <p className='link'>About</p>
        <p className='link'>Store</p>
      </div>

     {/* Right */}
      <div className='flex space-x-4 items-center'>
        <p className='link'>Gmail</p>
        <p className='link'>Images</p>
        
        {/* Icon */}
        {/* Avatar */}
      </div>
     </header>

     {/* Body */}

     {/* Footer */}

    </div>
  )
}
