import Head from 'next/head';
import Avatar from '../components/Avatar';
import { Squares2X2Icon } from "@heroicons/react/24/solid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* Header */}

     <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
      {/* Left */}
      <div className='flex space-x-4 items-center'>
        <p className='link'>About</p>
        <p className='link'>Store</p>
      </div>

     {/* Right */}
      <div className='flex space-x-4 items-center'>
        <p className='link'>Gmail</p>
        <p className='link'>Images</p>
        
        {/* Icon */}
        <Squares2X2Icon className="h-8 w-8 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

        <Avatar url="https://upload.wikimedia.org/wikipedia/en/6/6f/KennyMcCormick.png" />
      </div>
     </header>

     {/* Body */}

     {/* Footer */}

    </div>
  )
}
